language: python
python:
  - "2.7"
# command to install dependencies
services:
  - mongodb
install:
  - pip install -r requirements.txt
  - pip install -r testing_requirements.txt
# command to run tests
env:
  - DJANGO_VERSION=1.5
before_script:
  - ./start_local_popit_api.bash
  - ./start_writeit_for_testing.bash
script:
  - python tests.py
